name: SurvivalFriend
version: 1.2.8
main: de.laurinhummel.survivalfriend.SF
api-version: '1.19'

commands:
  menusf:
    description: Opens the menu to (de)activate features of this plugin
    usage: /menusf
  compass:
    description: Receive a compass pointing to a location
    usage: /compass <player>|<x> <z>
    aliases:
      - cp
      - comp
  enderchest:
    description: Open your ender chest, wherever you are
    usage: /ec
    aliases:
      - ec
  workbench:
    description: Opens a crafting table
    usage: /wb
    aliases:
      - wb
      - ct
      - craftingtable
